spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

luna:
  ftp:
    # \u81EA\u5B9A\u4E49\u8DEF\u5F84
    basePath: /pub/luna/
    conf: /pub/conf/
    picture: /pub/picture/
    voice: /pub/voice/
    #\u5730\u5740
    host: xxx
    # \u672C\u5730\u4E34\u65F6\u8DEF\u5F84
    local: xxx
    #\u5BC6\u7801
    password: xxx
    #\u7AEF\u53E3
    port: 21
    #\u7528\u6237\u540D
    username: xxx

    file:
      name: luna
      version: 1.0
      copyrightYear: 2020
      profile: luna
      addressEnabled: true

    http:
      username: luna
      password: czy1024