# smms\u56FE\u5E8A
luna:
  smms:
    authorizationCode: NFfqBMvYH6RfXaqEgjo79oDfQ7Ckrchg
    password: qyEF63QVT4!NwT9
    username: luna_nov

spring:
  # elasticsearch
  elasticsearch:
    rest:
      username: luna
      password: czy1024
      # 集群
      uris: [http://localhost:9200]
      connection-timeout: 5000
      read-timeout: 30000